### ISSUE TITLE
Could not pass event PlayerRespawnEvent to SplitWorld v3.0.0

### ISSUE THREAD

**Issue by BenKennish** [snaco/split-world-plugin#2]
Using Minecraft 1.21.1 (using Docker Image https://github.com/itzg/docker-minecraft-server)
Paper 1.21.1-119-master@7cd4f2c

Getting an error message to the console every time a player spawns into the world:

```
[10:23:40 ERROR]: Could not pass event PlayerSpawnLocationEvent to SplitWorld v3.0.0
java.lang.NumberFormatException: For input string: "[{x=140},"
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source) ~[?:?]
        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(Unknown Source) ~[?:?]
        at java.base/java.lang.Double.parseDouble(Unknown Source) ~[?:?]
        at SplitWorld-plugin-3.0.0.jar/tech.snaco.SplitWorld.SplitWorld$onSpawn$coordinates$2.invoke(SplitWorld.kt:357) ~[SplitWorld-plugin-3.0.0.jar:?]
        at SplitWorld-plugin-3.0.0.jar/tech.snaco.SplitWorld.SplitWorld$onSpawn$coordinates$2.invoke(SplitWorld.kt:357) ~[SplitWorld-plugin-3.0.0.jar:?]
        at SplitWorld-plugin-3.0.0.jar/tech.snaco.SplitWorld.SplitWorld.onSpawn$lambda$6(SplitWorld.kt:357) ~[SplitWorld-plugin-3.0.0.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
        at SplitWorld-plugin-3.0.0.jar/tech.snaco.SplitWorld.SplitWorld.onSpawn(SplitWorld.kt:357) ~[SplitWorld-plugin-3.0.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor24.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:272) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

Plugin seems to work fine otherwise but I haven't tested thoroughly.  Is this plugin still in development?  I think it's really cool and would like to use it if possible so that my sons can easily experience creative mode and survival mode on the same world.

Thanks, Ben

**Comment by BenKennish** [comment]
Btw I might be interested in contributing code to this project if you would like some help.

**Comment by BenKennish** [comment]
Is this project abandoned?

**Comment by snaco** [comment]
It's aliiiiive, sorry life has been busy and hectic but I just merged fix for that and will release the updated version soon.

**Comment by BenKennish** [comment]
ooh yay thank you! 😁
